#lang racket
(define lista(list 0 1 2 3 4 5 6 7))
(define (Cabezera lista)
  (car lista))
(define (Cuerpo lista)
  (cdr lista))
(define (agregar elemento lista)
  (cons elemento lista))
(display "Lista")
(newline)
(display lista)
(newline)
(display "cabezera ")
(newline)
(Cabezera lista)
(display "Cuerpo de la lista")
(newline)
(Cuerpo lista)
(display "agregando el numero 700 a la lista")
(newline)
(agregar 700 lista)
